version: 2.1
commands:
  npm-run:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "World"
    steps:
      - run: echo Hello 

orbs:
    node: circleci/node@5.0.0

workflows:
  run-deploy:
    jobs:
      - node/test
      - node/run:
          npm-run: deploy
          filters:
            branches:
              only: main
          requires:
            - node/test
