version: 2.1

jobs:  
  build:
    working_directory: ~/repo
    docker:
      - image: node:16.14.0-alpine3.14

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - add_ssh_keys:
          fingerprints:
            - "be:e3:f5:4a:43:d6:1f:ea:5b:0a:60:ef:15:cd:da:62"
            
      - run:
          name: Install apks
          command: apk add openssh git

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Deploy to gh-pages
          command: npm run deploy

  test:
    working_directory: ~/repo
    docker:
      - image: node:16.14.0-alpine3.14

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Run lint
          command: npm run lint

      - run:
          name: Run test
          command: npm run test   

workflow:
  build_and_test:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              only: main
          requires:
            - test
