version: 2.1
orbs:
  node: circleci/node@5.0.0

workflows:
  run-deploy:
    jobs:
      - node/test
      - node/run:
          npm-run: deploy
          filters:
            branches:
              only: main
          requires:
            - node/test
jobs:
  node/run:
    executor:
      name: node/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "be:e3:f5:4a:43:d6:1f:ea:5b:0a:60:ef:15:cd:da:62"

