version: 2.1
orbs:
  node: circleci/node@5.0

jobs:  
  test:
    executor:
      name: node/default
      tag: '16.14'
    steps:
      - add_ssh_keys:
          fingerprints:
            - "be:e3:f5:4a:43:d6:1f:ea:5b:0a:60:ef:15:cd:da:62"
      - checkout
      - node/install-packages
      - run:
          command: npm run test

workflows:
  run-npm-command:
    jobs:
      - node/run:
          npm-run: deploy
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              only: main
          requires:
            - test
      - test:
          filters:
            branches:
              ignore: gh-pages
            tags:
              only: /.*/