version: 2.1
orbs:
  node: circleci/node@5.0.0

workflows:
  run-deploy:
    jobs:
      - node/test
      - node/run:
          npm-run: deploy
          filters:
            branches:
              only: main
          requires:
            - node/test
