version: 2.1
orbs:
  node: circleci/node@5.0
jobs:
  deploy:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "be:e3:f5:4a:43:d6:1f:ea:5b:0a:60:ef:15:cd:da:62"

workflows:
  test_and_deploy:
    jobs:
      - node/test
      - deploy:
          filters:
            branches:
              only: main
      - node/run:
          npm-run: deploy
          filters:
            branches:
              only: main
          requires:
            - node/test
            - deploy
