version: 2.1
orbs:
  node: circleci/node@5.0
jobs:
  deploy:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - add_ssh_keys

workflows:
  test_and_deploy:
    jobs:
      - node/test
      - deploy:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              only: main
      - node/run:
          npm-run: deploy
          requires:
            - node/test
            - deploy
