version: 2.1
orbs:
  node: circleci/node@5.0
jobs:
  setup: &setup
    executor:
      name: node/default
      tag: '16.14'
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "be:e3:f5:4a:43:d6:1f:ea:5b:0a:60:ef:15:cd:da:62"
      - node/install-packages:
          cache-path: ~/project/node_modules

  node/run:
    <<: *setup

workflows:
  test_and_deploy:
    jobs:
      - node/run:
          npm-run: deploy
          requires:
            - node/test
      - node/test
