
version: 2.1
orbs:
  node: circleci/node@5.0.0

jobs:
  build_and_deploy: &build_and_deploy
    docker:
      - image: circleci/node:14

    steps:

      - checkout

      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install

      - run:
          name: Run terraform
          command: |
            echo "oi"
  autodeploy_qa:
    <<: *build_and_deploy
    environment:
      ENVIRONMENT: "qa"

workflows:
  ci:
    jobs:
      - autodeploy_qa:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              only: main
          requires:
            - node/test
            - node/run
      - node/run:
          npm-run: lint 
          requires:
            - node/test
      - node/test
